# Generated by Django 6.1.1 on 2026-09-18 06:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('university', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=30, null=True)),
                ('budget_min', models.PositiveIntegerField(default=0)),
                ('budget_max', models.PositiveIntegerField(default=300000)),
                ('location_preference', models.CharField(blank=True, default='', max_length=255)),
                ('sleep_habit', models.CharField(blank=True, choices=[('Night Owl', 'Night Owl'), ('Early Bird', 'Early Bird')], max_length=30, null=True)),
                ('cleanliness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('socializing', models.CharField(blank=True, choices=[('Guests often', 'Guests often'), ('Rarely', 'Rarely')], max_length=30, null=True)),
                ('smoking', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True)),
                ('noise_level', models.CharField(blank=True, choices=[('Quiet', 'Quiet'), ('Moderate', 'Moderate'), ('Lively', 'Lively')], max_length=30, null=True)),
                ('study_time', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Night', 'Night'), ('Varies', 'Varies')], max_length=30, null=True)),
                ('drinking_habit', models.CharField(blank=True, choices=[('Often', 'Often'), ('Socially', 'Socially'), ('Rarely/Never', 'Rarely/Never')], max_length=30, null=True)),
                ('pets_preference', models.CharField(blank=True, choices=[('Love them', 'Love them'), ('Okay with them', 'Okay with them'), ('Prefer no pets', 'Prefer no pets')], max_length=30, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('searching_for', models.CharField(choices=[('Looking for Roommate', 'Looking for Roommate'), ('Listing a Space', 'Listing a Space'), ('Already Matched', 'Already Matched')], default='Looking for Roommate', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
            },
        ),
    ]
