# Generated by Django 6.1.1 on 2026-09-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'ordering': ['created_at'], 'verbose_name': 'Device Token', 'verbose_name_plural': 'Device Tokens'},
        ),
    ]
